[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "openai>=1.102.0",
    "stellar-sdk>=13.0.0",
    "uvicorn>=0.32.0",
]
